name = Sudaka Articulos
description = Un layout para usar en la vista de articulos y contenidos en sitio americaleatina.org
preview = preview.png
template = sudaka-art-layout

regions[branding]       = Marca
regions[principal]	= Barra de Usuario
regions[banner]		= Banner
regions[navigation]     = Barra de Navegación
regions[highlighted]    = Destacados
regions[help]           = Ayuda
regions[content]        = Contenido
regions[sidebar_right] = Lateral Derecha
regions[pre_footer_1]   = Pre Footer-1
regions[pre_footer_2]   = Pre Footer-2
regions[pre_footer_3]   = Pre Footer-3
regions[footer]         = Footer


; Stylesheets
stylesheets[all][] = css/layouts/sudaka-art/sudaka-art.layout.css
stylesheets[all][] = css/layouts/sudaka-art/sudaka-art.layout.no-query.css
stylesheets[all][] = css/layouts/sudaka-art/leatina-sudaka-art.layout.css
